[tool.poetry]
name = "sfat"
version = "0.1.0"
description = ""
authors = ["pondelion"]

[tool.poetry.dependencies]
python = "^3.8"
streamlit = "^0.86.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
